FROM python:3-alpine

ADD requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

WORKDIR /app

ADD ./entrypoint.sh /app/entrypoint.sh

ADD ./app.py /app/app.py

ADD ./templates/ /app/templates/

RUN mkdir /app/log/

CMD /app/entrypoint.sh

